version: '3.9'

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus-svc:
    image: prometheus-img:latest
    container_name: prometheus-svc
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 0.0.0.0:${PROMETHEUS_PORT}:9090
    networks:
      - monitoring-network
    labels:
      org.label-schema.group: "monitoring"

  node-exporter-svc:
    image: node-exporter-img:latest
    container_name: node-exporter-svc
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 0.0.0.0:${NODE_EXPORTER_PORT}:9100
    networks:
      - monitoring-network
    labels:
      org.label-schema.group: "monitoring"

  cadvisor-svc:
    image: cadvisor-img:latest
    container_name: cadvisor-svc
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    ports:
      - 0.0.0.0:${CADVISOR_PORT}:8080
    networks:
      - monitoring-network
    labels:
      org.label-schema.group: "monitoring"
  
  # alertmanager:
  #   image: prom/alertmanager:v0.20.0
  #   container_name: alertmanager
  #   volumes:
  #     - ./alertmanager:/etc/alertmanager
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #   restart: unless-stopped
  #   expose:
  #     - 9093
  #   networks:
  #     - monitoring-network
  #   labels:
  #     org.label-schema.group: "monitoring"

  grafana-svc:
    image: grafana-img:latest
    container_name: grafana-svc
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 0.0.0.0:${GRAFANA_PORT}:3000
    networks:
      - monitoring-network
    labels:
      org.label-schema.group: "monitoring"
